package soft.accueil.entities;
// Generated 16 janv. 2018 13:43:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Batiment generated by hbm2java
 */
@Entity
@Table(name="batiment"
    ,catalog="accueilsoft"
)
public class Batiment  implements java.io.Serializable {


     private Integer idbatiment;
     private String code;
     private String libelle;
     private String statut;
     private Integer idutilisateur;
     private Set<Bureau> bureaus = new HashSet<Bureau>(0);

    public Batiment() {
    }

    public Batiment(String code, String libelle, String statut, Integer idutilisateur, Set<Bureau> bureaus) {
       this.code = code;
       this.libelle = libelle;
       this.statut = statut;
       this.idutilisateur = idutilisateur;
       this.bureaus = bureaus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idbatiment", unique=true, nullable=false)
    public Integer getIdbatiment() {
        return this.idbatiment;
    }
    
    public void setIdbatiment(Integer idbatiment) {
        this.idbatiment = idbatiment;
    }

    
    @Column(name="code", length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle")
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

    
    @Column(name="idutilisateur")
    public Integer getIdutilisateur() {
        return this.idutilisateur;
    }
    
    public void setIdutilisateur(Integer idutilisateur) {
        this.idutilisateur = idutilisateur;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="batiment")
    public Set<Bureau> getBureaus() {
        return this.bureaus;
    }
    
    public void setBureaus(Set<Bureau> bureaus) {
        this.bureaus = bureaus;
    }




}


