package soft.accueil.entities;
// Generated 16 janv. 2018 13:43:22 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Colis generated by hbm2java
 */
@Entity
@Table(name="colis"
    ,catalog="accueilsoft"
)
public class Colis  implements java.io.Serializable {


     private Integer idcolis;
     private Bureau bureau;
     private Employe employe;
     private String noms;
     private String prenoms;
     private String piece;
     private Date dateDepot;
     private String description;
     private String statut;
     private Integer idutilisateur;
     private String numeropiece;
     private String numerocolis;

    public Colis() {
    }

    public Colis(Bureau bureau, Employe employe, String noms, String prenoms, String piece, Date dateDepot, String description, String statut, Integer idutilisateur, String numeropiece, String numerocolis) {
       this.bureau = bureau;
       this.employe = employe;
       this.noms = noms;
       this.prenoms = prenoms;
       this.piece = piece;
       this.dateDepot = dateDepot;
       this.description = description;
       this.statut = statut;
       this.idutilisateur = idutilisateur;
       this.numeropiece = numeropiece;
       this.numerocolis = numerocolis;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcolis", unique=true, nullable=false)
    public Integer getIdcolis() {
        return this.idcolis;
    }
    
    public void setIdcolis(Integer idcolis) {
        this.idcolis = idcolis;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idbureau")
    public Bureau getBureau() {
        return this.bureau;
    }
    
    public void setBureau(Bureau bureau) {
        this.bureau = bureau;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idemploye")
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }

    
    @Column(name="noms", length=45)
    public String getNoms() {
        return this.noms;
    }
    
    public void setNoms(String noms) {
        this.noms = noms;
    }

    
    @Column(name="prenoms", length=45)
    public String getPrenoms() {
        return this.prenoms;
    }
    
    public void setPrenoms(String prenoms) {
        this.prenoms = prenoms;
    }

    
    @Column(name="piece")
    public String getPiece() {
        return this.piece;
    }
    
    public void setPiece(String piece) {
        this.piece = piece;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_depot", length=19)
    public Date getDateDepot() {
        return this.dateDepot;
    }
    
    public void setDateDepot(Date dateDepot) {
        this.dateDepot = dateDepot;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

    
    @Column(name="idutilisateur")
    public Integer getIdutilisateur() {
        return this.idutilisateur;
    }
    
    public void setIdutilisateur(Integer idutilisateur) {
        this.idutilisateur = idutilisateur;
    }

    
    @Column(name="numeropiece", length=45)
    public String getNumeropiece() {
        return this.numeropiece;
    }
    
    public void setNumeropiece(String numeropiece) {
        this.numeropiece = numeropiece;
    }

    
    @Column(name="numerocolis", length=45)
    public String getNumerocolis() {
        return this.numerocolis;
    }
    
    public void setNumerocolis(String numerocolis) {
        this.numerocolis = numerocolis;
    }




}


