package soft.accueil.entities;
// Generated 16 janv. 2018 13:43:22 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entree generated by hbm2java
 */
@Entity
@Table(name="entree"
    ,catalog="accueilsoft"
)
public class Entree  implements java.io.Serializable {


     private Integer identree;
     private Bureau bureau;
     private Employe employe;
     private EntreeBadge entreeBadge;
     private Visite visite;
     private Date heureDentree;
     private Date heureSortie;
     private String nomComplet;
     private String numeroDePiece;
     private String motif;
     private String statut;
     private String piece;
     private Integer idutilisateur;
     private Date heureEntreeBureau;
     private Date heureSortieBureau;
     private String entreprise;
     private Set<PieceOubliee> pieceOubliees = new HashSet<PieceOubliee>(0);

    public Entree() {
    }

    public Entree(Bureau bureau, Employe employe, EntreeBadge entreeBadge, Visite visite, Date heureDentree, Date heureSortie, String nomComplet, String numeroDePiece, String motif, String statut, String piece, Integer idutilisateur, Date heureEntreeBureau, Date heureSortieBureau, String entreprise, Set<PieceOubliee> pieceOubliees) {
       this.bureau = bureau;
       this.employe = employe;
       this.entreeBadge = entreeBadge;
       this.visite = visite;
       this.heureDentree = heureDentree;
       this.heureSortie = heureSortie;
       this.nomComplet = nomComplet;
       this.numeroDePiece = numeroDePiece;
       this.motif = motif;
       this.statut = statut;
       this.piece = piece;
       this.idutilisateur = idutilisateur;
       this.heureEntreeBureau = heureEntreeBureau;
       this.heureSortieBureau = heureSortieBureau;
       this.entreprise = entreprise;
       this.pieceOubliees = pieceOubliees;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="identree", unique=true, nullable=false)
    public Integer getIdentree() {
        return this.identree;
    }
    
    public void setIdentree(Integer identree) {
        this.identree = identree;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idbureau_concerne")
    public Bureau getBureau() {
        return this.bureau;
    }
    
    public void setBureau(Bureau bureau) {
        this.bureau = bureau;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idemploye_concerne")
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="identree_badge")
    public EntreeBadge getEntreeBadge() {
        return this.entreeBadge;
    }
    
    public void setEntreeBadge(EntreeBadge entreeBadge) {
        this.entreeBadge = entreeBadge;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idvisite")
    public Visite getVisite() {
        return this.visite;
    }
    
    public void setVisite(Visite visite) {
        this.visite = visite;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="heure_dentree", length=19)
    public Date getHeureDentree() {
        return this.heureDentree;
    }
    
    public void setHeureDentree(Date heureDentree) {
        this.heureDentree = heureDentree;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="heure_sortie", length=19)
    public Date getHeureSortie() {
        return this.heureSortie;
    }
    
    public void setHeureSortie(Date heureSortie) {
        this.heureSortie = heureSortie;
    }

    
    @Column(name="nom_complet")
    public String getNomComplet() {
        return this.nomComplet;
    }
    
    public void setNomComplet(String nomComplet) {
        this.nomComplet = nomComplet;
    }

    
    @Column(name="numero_de_piece", length=45)
    public String getNumeroDePiece() {
        return this.numeroDePiece;
    }
    
    public void setNumeroDePiece(String numeroDePiece) {
        this.numeroDePiece = numeroDePiece;
    }

    
    @Column(name="motif", length=16777215)
    public String getMotif() {
        return this.motif;
    }
    
    public void setMotif(String motif) {
        this.motif = motif;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

    
    @Column(name="piece", length=105)
    public String getPiece() {
        return this.piece;
    }
    
    public void setPiece(String piece) {
        this.piece = piece;
    }

    
    @Column(name="idutilisateur")
    public Integer getIdutilisateur() {
        return this.idutilisateur;
    }
    
    public void setIdutilisateur(Integer idutilisateur) {
        this.idutilisateur = idutilisateur;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="heure_entree_bureau", length=19)
    public Date getHeureEntreeBureau() {
        return this.heureEntreeBureau;
    }
    
    public void setHeureEntreeBureau(Date heureEntreeBureau) {
        this.heureEntreeBureau = heureEntreeBureau;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="heure_sortie_bureau", length=19)
    public Date getHeureSortieBureau() {
        return this.heureSortieBureau;
    }
    
    public void setHeureSortieBureau(Date heureSortieBureau) {
        this.heureSortieBureau = heureSortieBureau;
    }

    
    @Column(name="entreprise")
    public String getEntreprise() {
        return this.entreprise;
    }
    
    public void setEntreprise(String entreprise) {
        this.entreprise = entreprise;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="entree")
    public Set<PieceOubliee> getPieceOubliees() {
        return this.pieceOubliees;
    }
    
    public void setPieceOubliees(Set<PieceOubliee> pieceOubliees) {
        this.pieceOubliees = pieceOubliees;
    }




}


