package soft.accueil.entities;
// Generated 16 janv. 2018 13:43:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EntreeBadge generated by hbm2java
 */
@Entity
@Table(name="entree_badge"
    ,catalog="accueilsoft"
)
public class EntreeBadge  implements java.io.Serializable {


     private Integer identreeBadge;
     private String numero;
     private String autreInformation;
     private String statut;
     private Integer idutilisateur;
     private Set<Entree> entrees = new HashSet<Entree>(0);

    public EntreeBadge() {
    }

    public EntreeBadge(String numero, String autreInformation, String statut, Integer idutilisateur, Set<Entree> entrees) {
       this.numero = numero;
       this.autreInformation = autreInformation;
       this.statut = statut;
       this.idutilisateur = idutilisateur;
       this.entrees = entrees;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="identree_badge", unique=true, nullable=false)
    public Integer getIdentreeBadge() {
        return this.identreeBadge;
    }
    
    public void setIdentreeBadge(Integer identreeBadge) {
        this.identreeBadge = identreeBadge;
    }

    
    @Column(name="numero")
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="autre_information", length=45)
    public String getAutreInformation() {
        return this.autreInformation;
    }
    
    public void setAutreInformation(String autreInformation) {
        this.autreInformation = autreInformation;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

    
    @Column(name="idutilisateur")
    public Integer getIdutilisateur() {
        return this.idutilisateur;
    }
    
    public void setIdutilisateur(Integer idutilisateur) {
        this.idutilisateur = idutilisateur;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="entreeBadge")
    public Set<Entree> getEntrees() {
        return this.entrees;
    }
    
    public void setEntrees(Set<Entree> entrees) {
        this.entrees = entrees;
    }




}


