package soft.accueil.entities;
// Generated 16 janv. 2018 13:43:22 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name="message"
    ,catalog="accueilsoft"
)
public class Message  implements java.io.Serializable {


     private Integer idmessage;
     private Employe employeByIdrecepteur;
     private Employe employeByIdemetteur;
     private String contenu;
     private Date dateEnvoi;
     private Date dateReception;

    public Message() {
    }

    public Message(Employe employeByIdrecepteur, Employe employeByIdemetteur, String contenu, Date dateEnvoi, Date dateReception) {
       this.employeByIdrecepteur = employeByIdrecepteur;
       this.employeByIdemetteur = employeByIdemetteur;
       this.contenu = contenu;
       this.dateEnvoi = dateEnvoi;
       this.dateReception = dateReception;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmessage", unique=true, nullable=false)
    public Integer getIdmessage() {
        return this.idmessage;
    }
    
    public void setIdmessage(Integer idmessage) {
        this.idmessage = idmessage;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idrecepteur")
    public Employe getEmployeByIdrecepteur() {
        return this.employeByIdrecepteur;
    }
    
    public void setEmployeByIdrecepteur(Employe employeByIdrecepteur) {
        this.employeByIdrecepteur = employeByIdrecepteur;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idemetteur")
    public Employe getEmployeByIdemetteur() {
        return this.employeByIdemetteur;
    }
    
    public void setEmployeByIdemetteur(Employe employeByIdemetteur) {
        this.employeByIdemetteur = employeByIdemetteur;
    }

    
    @Column(name="contenu")
    public String getContenu() {
        return this.contenu;
    }
    
    public void setContenu(String contenu) {
        this.contenu = contenu;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_envoi", length=19)
    public Date getDateEnvoi() {
        return this.dateEnvoi;
    }
    
    public void setDateEnvoi(Date dateEnvoi) {
        this.dateEnvoi = dateEnvoi;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_reception", length=19)
    public Date getDateReception() {
        return this.dateReception;
    }
    
    public void setDateReception(Date dateReception) {
        this.dateReception = dateReception;
    }




}


