package soft.accueil.entities;
// Generated 16 janv. 2018 13:43:22 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PieceOubliee generated by hbm2java
 */
@Entity
@Table(name="piece_oubliee"
    ,catalog="accueilsoft"
)
public class PieceOubliee  implements java.io.Serializable {


     private Integer idpieceOubliee;
     private Entree entree;
     private String numero;
     private String image;
     private Date dateOubli;
     private String statut;
     private String piece;
     private String nomComplet;

    public PieceOubliee() {
    }

    public PieceOubliee(Entree entree, String numero, String image, Date dateOubli, String statut, String piece, String nomComplet) {
       this.entree = entree;
       this.numero = numero;
       this.image = image;
       this.dateOubli = dateOubli;
       this.statut = statut;
       this.piece = piece;
       this.nomComplet = nomComplet;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idpiece_oubliee", unique=true, nullable=false)
    public Integer getIdpieceOubliee() {
        return this.idpieceOubliee;
    }
    
    public void setIdpieceOubliee(Integer idpieceOubliee) {
        this.idpieceOubliee = idpieceOubliee;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="identree")
    public Entree getEntree() {
        return this.entree;
    }
    
    public void setEntree(Entree entree) {
        this.entree = entree;
    }

    
    @Column(name="numero", length=45)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="image")
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_oubli", length=19)
    public Date getDateOubli() {
        return this.dateOubli;
    }
    
    public void setDateOubli(Date dateOubli) {
        this.dateOubli = dateOubli;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

    
    @Column(name="piece", length=105)
    public String getPiece() {
        return this.piece;
    }
    
    public void setPiece(String piece) {
        this.piece = piece;
    }

    
    @Column(name="nom_complet")
    public String getNomComplet() {
        return this.nomComplet;
    }
    
    public void setNomComplet(String nomComplet) {
        this.nomComplet = nomComplet;
    }




}


