package soft.accueil.entities;
// Generated 16 janv. 2018 13:43:22 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name="utilisateur"
    ,catalog="accueilsoft"
    , uniqueConstraints = @UniqueConstraint(columnNames="login") 
)
public class Utilisateur  implements java.io.Serializable {


     private Integer idutilisateur;
     private Employe employe;
     private UtilisateurProfil utilisateurProfil;
     private String login;
     private String passe;
     private Date dateCreation;
     private Boolean isConnectee;
     private Boolean passeChanged;
     private Boolean isActif;
     private String statut;
     private Integer idcreateur;

    public Utilisateur() {
    }

    public Utilisateur(Employe employe, UtilisateurProfil utilisateurProfil, String login, String passe, Date dateCreation, Boolean isConnectee, Boolean passeChanged, Boolean isActif, String statut, Integer idcreateur) {
       this.employe = employe;
       this.utilisateurProfil = utilisateurProfil;
       this.login = login;
       this.passe = passe;
       this.dateCreation = dateCreation;
       this.isConnectee = isConnectee;
       this.passeChanged = passeChanged;
       this.isActif = isActif;
       this.statut = statut;
       this.idcreateur = idcreateur;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idutilisateur", unique=true, nullable=false)
    public Integer getIdutilisateur() {
        return this.idutilisateur;
    }
    
    public void setIdutilisateur(Integer idutilisateur) {
        this.idutilisateur = idutilisateur;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idemploye")
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idprofil")
    public UtilisateurProfil getUtilisateurProfil() {
        return this.utilisateurProfil;
    }
    
    public void setUtilisateurProfil(UtilisateurProfil utilisateurProfil) {
        this.utilisateurProfil = utilisateurProfil;
    }

    
    @Column(name="login", unique=true, length=45)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="passe")
    public String getPasse() {
        return this.passe;
    }
    
    public void setPasse(String passe) {
        this.passe = passe;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_creation", length=19)
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }

    
    @Column(name="is_connectee")
    public Boolean getIsConnectee() {
        return this.isConnectee;
    }
    
    public void setIsConnectee(Boolean isConnectee) {
        this.isConnectee = isConnectee;
    }

    
    @Column(name="passe_changed")
    public Boolean getPasseChanged() {
        return this.passeChanged;
    }
    
    public void setPasseChanged(Boolean passeChanged) {
        this.passeChanged = passeChanged;
    }

    
    @Column(name="is_actif")
    public Boolean getIsActif() {
        return this.isActif;
    }
    
    public void setIsActif(Boolean isActif) {
        this.isActif = isActif;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

    
    @Column(name="idcreateur")
    public Integer getIdcreateur() {
        return this.idcreateur;
    }
    
    public void setIdcreateur(Integer idcreateur) {
        this.idcreateur = idcreateur;
    }




}


