package soft.accueil.entities;
// Generated 16 janv. 2018 13:43:22 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Visite generated by hbm2java
 */
@Entity
@Table(name="visite"
    ,catalog="accueilsoft"
)
public class Visite  implements java.io.Serializable {


     private Integer idvisite;
     private Employe employe;
     private String nomPersonneAttendue;
     private String motif;
     private Date heureAttendue;
     private String statut;
     private Boolean laisserPasser;
     private String commentaire;
     private Integer idutilisateur;
     private String entreprise;
     private Set<Entree> entrees = new HashSet<Entree>(0);

    public Visite() {
    }

    public Visite(Employe employe, String nomPersonneAttendue, String motif, Date heureAttendue, String statut, Boolean laisserPasser, String commentaire, Integer idutilisateur, String entreprise, Set<Entree> entrees) {
       this.employe = employe;
       this.nomPersonneAttendue = nomPersonneAttendue;
       this.motif = motif;
       this.heureAttendue = heureAttendue;
       this.statut = statut;
       this.laisserPasser = laisserPasser;
       this.commentaire = commentaire;
       this.idutilisateur = idutilisateur;
       this.entreprise = entreprise;
       this.entrees = entrees;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idvisite", unique=true, nullable=false)
    public Integer getIdvisite() {
        return this.idvisite;
    }
    
    public void setIdvisite(Integer idvisite) {
        this.idvisite = idvisite;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idemploye")
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }

    
    @Column(name="nom_personne_attendue")
    public String getNomPersonneAttendue() {
        return this.nomPersonneAttendue;
    }
    
    public void setNomPersonneAttendue(String nomPersonneAttendue) {
        this.nomPersonneAttendue = nomPersonneAttendue;
    }

    
    @Column(name="motif", length=45)
    public String getMotif() {
        return this.motif;
    }
    
    public void setMotif(String motif) {
        this.motif = motif;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="heure_attendue", length=19)
    public Date getHeureAttendue() {
        return this.heureAttendue;
    }
    
    public void setHeureAttendue(Date heureAttendue) {
        this.heureAttendue = heureAttendue;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

    
    @Column(name="laisser_passer")
    public Boolean getLaisserPasser() {
        return this.laisserPasser;
    }
    
    public void setLaisserPasser(Boolean laisserPasser) {
        this.laisserPasser = laisserPasser;
    }

    
    @Column(name="commentaire")
    public String getCommentaire() {
        return this.commentaire;
    }
    
    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }

    
    @Column(name="idutilisateur")
    public Integer getIdutilisateur() {
        return this.idutilisateur;
    }
    
    public void setIdutilisateur(Integer idutilisateur) {
        this.idutilisateur = idutilisateur;
    }

    
    @Column(name="entreprise")
    public String getEntreprise() {
        return this.entreprise;
    }
    
    public void setEntreprise(String entreprise) {
        this.entreprise = entreprise;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="visite")
    public Set<Entree> getEntrees() {
        return this.entrees;
    }
    
    public void setEntrees(Set<Entree> entrees) {
        this.entrees = entrees;
    }




}


